 const CHARECTOR = "CHARECTOR";
 const ACTION = "ACTION";
 const PARANTHETICAL = "PARANTHETICAL";
 const DIALOGUE = "DIALOGUE";
 const SCENE_HEADING = "SCENE_HEADING"
 const TRANSITION = "TRANSITION"
 export default {
    CHARECTOR,
    ACTION,
    PARANTHETICAL,
    DIALOGUE,
    SCENE_HEADING,
    TRANSITION
 }